name: Build and maybe upload PyPI package

on:
    push:
        branches: [main]
        tags: ["*"]
    pull_request:
        branches: [main]
    release:
        types: [published]
    workflow_dispatch:

env:
    FORCE_COLOR: "1" # Make tools pretty.

permissions:
    contents: read

jobs:
    # Always build and lint
    build-package:
        name: Build package 📦
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout repository 🛎"
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                fetch-depth: 0
                persist-credentials: false

            - name: "Build and inspect package 🛠"
              uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v3.0.1

    # Upload to Test PyPI on every commit on main.
    release-test-pypi:
        name: Publish in-dev package to test.pypi.org
        environment: release-test-pypi
        permissions:
            id-token: write
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: build-package

        steps:
            - name: "Download package built in previous job 📥"
              uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
              with:
                name: Packages
                path: dist
            - name: "Upload package to Test PyPI 🚀"
              uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
              with:
                repository-url: https://test.pypi.org/legacy/

    # Upload to real PyPI on GitHub Releases.
    release-pypi:
        name: Publish released package to pypi.org 🚀
        environment:
            name: release-pypi
            url: https://pypi.org/project/accessible-pygments/
        permissions:
            id-token: write
        if: github.repository_owner == 'Quansight-Labs' && github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        needs: build-package

        steps:
            - name: "Download packages built in previous job 📥"
              uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
              with:
                name: Packages
                path: dist

            - name: "Upload package to PyPI 🚀"
              uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
              with:
                print-hash: true
                verbose: true
